name = "KM3Acoustics"
uuid = "e21ca9ae-d296-42ad-b37a-731a42f35e62"
authors = ["Markus Pirke <markus.pirke@web.de> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[compat]
WAV = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
